version: "3"
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx/build
            dockerfile: Dockerfile
        volumes:
            - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/etc/conf.d:/etc/nginx/conf.d
            - ./nginx/etc/ssl/private:/etc/ssl/private
            - ./nginx/etc/ssl/certs:/etc/ssl/certs
            - ./nginx/var/www/localhost/public_html:/usr/share/nginx/html
            - ./nginx/var/log/nginx:/var/log/nginx
        ports:
            - 80:80
#            - 443:443         
        networks:
            - nginx-network

networks:
    nginx-network:
        driver: bridge
